# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ae82181c1410d45cf8a5c609ff2b5ab1ea814d68490de3c6fb3ff071a368f51953c3269c0904ea78a97ed674ed8be7b5c47ec86c45245177ba3babb67440fb4

test:
  secret_key_base: 863bc41dc53f6819473a0515bd9d379825f801e9e3274c6576d4718cefe5f5bbc670f429dad01f7ce4bbc68afaf0ead402a0cfb3d47c91703ccaff8da123abf2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
